version: 0.0
os: linux
files:
  - source: /assets
    destination: /var/www/html/assets
  - source: /css
    destination: /var/www/html/css
  - source: /fonts
    destination: /var/www/html/fonts
  - source: /img
    destination: /var/www/html/img
  - source: /js
    destination:  /var/www/html/js
  - source: /scss
    destination:  /var/www/html/scss
  - source: /vendors
    destination:  /var/www/html/vendors
  - source: /index.php
    destination:  /var/www/html/
  

    
hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 300
      runas: root

  
